image_dictionary = {
    ".jpg": "JPEG image file",
    ".png": "Portable Network Graphics file",
    ".gif": "Graphics Interchange Format file",
    ".bmp": "Bitmap image file",
    ".tiff": "Tagged Image File Format",
    ".svg": "Scalable Vector Graphics file",
    ".ico": "Icon file",
    ".webp": "WebP image file",
    ".raw": "Raw image file",
    ".pdf": "Portable Document Format file",
    "ICO" : "Icon File",
    "WebP" : "WebP Image",
    "HEIC/HEIF" : "High Efficiency Image Format",
    "JP2" : "JPEG 2000 Image",
    "PBM" : "Portable Bitmap Image",
    "PGM" : "Portable Graymap Image",
    "PPM" : "Portable Pixmap Image",
    "XBM" : "X BitMap Image",
    "WBMP" : "Wireless Bitmap Image"
}

video_dictionary = {
    "mp4": "MPEG:4 video file",
    "avi": "Audio Video Interleave file",
    "mov": "QuickTime video file",
    "mkv": "Matroska video file",
    "flv": "Flash video file",
    "wmv": "Windows Media Video file",
    "mpg": "MPEG video file",
    "webm": "WebM video file",
    "3gp": "3GPP video file",
    "m4v": "MPEG:4 video file",
    "ogg": "Ogg video file",
    "ts": "MPEG transport stream file",
    "VOB" : "DVD Video Object",
    "RM" : "RealMedia",
    "SWF" : "Shockwave Flash",
    "ASF" : "Advanced Systems Format",
    "MTS" : "AVCHD Video",
    "F4V" : "Flash Video",
    "MXF" : "Material Exchange Format",
    "AMV" : "Anime Music Video"
}

audio_dictionay = {
    "MP3" : "MPEG Audio Layer:3",
    "WAV" : "Waveform Audio File Format",
    "FLAC" : "Free Lossless Audio Codec",
    "AAC" : "Advanced Audio Coding",
    "OGG" : "Ogg Vorbis",
    "WMA" : "Windows Media Audio",
    "AIFF" : "Audio Interchange File Format",
    "ALAC" : "Apple Lossless Audio Codec",
    "M4A" : "MPEG:4 Audio Layer",
    "AC3" : "Audio Coding 3",
    "AMR" : "Adaptive Multi : Rate Audio Codec",
    "MP2" : "MPEG Audio Layer : 2",
    "AU" : "Audio File",
    "MIDI" : "Musical Instrument Digital Interface",
    "OPUS" : "Opus Audio Codec",
    "APE" : "Monkey's Audio",
    "DSD" : "Direct Stream Digital",
    "MPGA" : "MPEG Audio",
    "RA" : "RealAudio",
    "WV" : "WavPack Audio",
    "CAF" : "Core Audio Format",
    "MPC" : "Musepack",
    "SPX" : "Speex Audio",
    "MP1" : "MPEG Audio Layer:1",
    "MOD" : "Module File",
    "SND" : "Sound File",
    "ADX" : "CRI Audio File",
    "GSM" : "GSM Audio File",
    "VQF" : "TwinVQ Audio",
    "TTA" : "True Audio",
    "SPC" : "Super Nintendo Audio File",
    "OPUS" : "Opus Audio File",
    "EAC3" : "Enhanced AC:3 Audio",
    "WavPack" : "WavPack Audio File",
    "WVX" : "WavPack Hybrid Lossless Audio",
    "MID" : "MIDI File",
    "DTS" : "Digital Theater Systems Audio File",
    "MKA" : "Matroska Audio File",
    "AMR:WB" : "Adaptive Multi:Rate Wideband Audio",
    "ATRAC" : "Adaptive Transform Acoustic Coding",
    "S3M" : "Scream Tracker 3 Module",
    "IT" : "Impulse Tracker Module",
    "XM" : "Extended Module",
    "NSF" : "NES Sound Format",
    "SID" : "Commodore 64 Audio File",
    "W64" : "Sony Wave64 Audio File",
    "3GA" : "3GPP Audio File",
    "ADPCM" : "Adaptive Differential Pulse Code Modulation",
    "SD2" : "Sound Designer II File",
    "VOC" : "Creative Voice File",
    "MPP" : "Musepack Compressed Audio File",
    "AMR:NB" : "Adaptive Multi:Rate Narrowband Audio",
    "RMI" : "RIFF MIDI File",
    "IFF" : "Interchange File Format",
    "MTM" : "MultiTracker Module",
    "S3Z" : "Compressed Scream Tracker 3 Module",
    "AIFC" : "Compressed Audio Interchange File Format",
    "RIFF" : "Resource Interchange File Format",
    "RNS" : "Reason Song File",
    "IRCAM" : "IRCAM Sound File",
    "PVF" : "Portable Voice Format",
    "ARR" : "Cubase Arrange File",
    "KAR": "Karaoke MIDI File",
    "OFR" : "OptimFROG Lossless Audio File",
    "PAF" : "Ensoniq PARIS Audio File",
    "AU/SND" : "Sun Audio File",
    "SDS" : "MIDI Sample Dump Standard File",
    "AIFF:C" : "AIFF:C Sound File",
    "WVE" : "Wondershare Filmora Project File",
    "MPC8" : "Musepack SV8 Audio File",
}

text_dictionary = {
    "TXT" : "Plain Text File",
    "CSV" : "Comma - Separated Values",
    "XML" : "Extensible Markup Language",
    "JSON" : "JavaScript Object Notation",
    "HTML" : "Hypertext Markup Language",
    "RTF" : "Rich Text Format",
    "DOC/DOCX" : "Microsoft Word Document",
    "PDF" : "Portable Document Format",
    "EPUB" : "Electronic Publication",
    "Markdown" : "Markdown Text Format"
}

file_extensions = {
    "EXE": "Executable File",
    "DLL": "Dynamic Link Library",
    "SYS": "System File",
    "APP": "Application File",
    "BAT": "Batch File",
    "SH": "Shell Script",
    "PS1": "PowerShell Script",
    "VBS": "VBScript File",
    "JAR": "Java Archive",
    "APK": "Android Package",
    "IPA": "iOS App Archive",
    "PY": "Python Script",
    "PYC": "Compiled Python File",
    "RB": "Ruby Script",
    "R": "R Script",
    "PL": "Perl Script",
    "C": "C Source Code File",
    "CPP": "C++ Source Code File",
    "H": "C/C++ Header File",
    "JAVA": "Java Source Code File",
    "JS": "JavaScript Source Code File",
    "CSS": "Cascading Style Sheet",
    "HTML": "Hypertext Markup Language File",
    "PHP": "PHP Script",
    "ASP/ASPX": "Active Server Page",
    "JSP": "JavaServer Pages File",
    "TS": "TypeScript Source Code File",
    "GO": "Go Source Code File",
    "SWIFT": "Swift Source Code File",
    "SCALA": "Scala Source Code File",
    "RUBY": "Ruby Source Code File",
    "PERL": "Perl Script",
    "LUA": "Lua Source Code File",
    "PLSQL": "PL/SQL Source Code File",
    "ASM": "Assembly Source Code File",
    "VB": "Visual Basic Source Code File",
    "VBSCRIPT": "VBScript File",
    "MATLAB": "MATLAB Source Code File",
    "OCTAVE": "Octave Script File",
    "F90": "Fortran 90 Source Code File",
    "F95": "Fortran 95 Source Code File",
    "BAT": "Windows Batch Script",
    "CMD": "Windows Command Script",
    "SWF": "Flash Animation File",
    "HTA": "HTML Application File",
    "IPA": "iOS App Archive",
    "APK": "Android Package File",
    "MSI": "Windows Installer Package",
    "DMG": "macOS Disk Image",
    "ISO": "Disk Image File"
}

system_file_formats = {
    "DLL": "Dynamic Link Library",
    "SYS": "System File",
    "EXE": "Executable File",
    "SYS": "Device Driver File",
    "INI": "Initialization File",
    "BAT": "Batch File",
    "CFG": "Configuration File",
    "INF": "Information File",
    "LIB": "Library File",
    "DRV": "Device Driver File",
    "SYS": "System Configuration File",
    "VXD": "Virtual Device Driver File",
    "DMP": "Dump File",
    "BAK": "Backup File",
    "NFO": "Information File",
    "REG": "Registry File",
    "BIN": "Binary File",
    "PRX": "Plugin File",
    "DAT": "Data File",
    "PNF": "Precompiled Setup Information File",
    "ICO": "Icon File",
    "OVL": "Overlay File",
    "MUI": "Multilingual User Interface File",
    "SFC": "System File Checker File",
    "BCD": "Boot Configuration Data File",
    "NLS": "National Language Support File",
    "WIM": "Windows Imaging Format File",
    "NT": "Windows NT File",
    "NTFS": "NTFS File System",
    "NTUSER": "NT User Data File",
    "PF": "Page File",
    "LOG": "Log File",
    "SAM": "Security Account Manager File",
    "TMP": "Temporary File",
    "SYS": "System Recovery File",
    "GZ": "Compressed File Archive",
    "P7M": "Digitally Encrypted Message File",
    "ROM": "Read-Only Memory Image File",
    "EFI": "Extensible Firmware Interface File",
    "BOOT": "Boot Sector File",
    "KEY": "Security Key File",
    "PRF": "Outlook Profile File",
    "CAT": "Security Catalog File",
    "MBR": "Master Boot Record",
    "VHDX": "Hyper-V Virtual Hard Disk File",
    "OST": "Outlook Offline Data File",
    "DLL": "Control Panel Extension File",
    "TTF": "TrueType Font File",
    "CUR": "Cursor Image File",
    "SYS": "Kernel System File"
}

adobe_file_formats = {
    "PSD": "Adobe Photoshop Document",
    "PSB": "Adobe Photoshop Big Document",
    "TIFF": "Tagged Image File Format",
    "JPEG": "Joint Photographic Experts Group",
    "PNG": "Portable Network Graphics",
    "GIF": "Graphics Interchange Format",
    "PDF": "Portable Document Format",
    "AI": "Adobe Illustrator File",
    "SVG": "Scalable Vector Graphics",
    "EPS": "Encapsulated PostScript",
    "INDD": "Adobe InDesign Document",
    "IDML": "Adobe InDesign Markup Language File",
    "PRPROJ": "Adobe Premiere Pro Project File",
    "MP4": "MPEG-4 Video File",
    "MOV": "QuickTime Movie",
    "AVI": "Audio Video Interleave",
    "MXF": "Material Exchange Format",
    "AEP": "Adobe After Effects Project File",
    "AEPX": "Adobe After Effects XML Project File",
    "AET": "Adobe After Effects Project Template",
    "XD": "Adobe XD Document",
    "WAV": "Waveform Audio File Format",
    "MP3": "MPEG Audio Layer 3",
    "AIFF": "Audio Interchange File Format",
    "FLAC": "Free Lossless Audio Codec"
}

microsoft_office_formats = {
    "DOC": "Word Document",
    "DOCX": "Word Open XML Document",
    "DOT": "Word Document Template",
    "DOTX": "Word Open XML Document Template",
    "RTF": "Rich Text Format",
    "XLS": "Excel Spreadsheet (Legacy)",
    "XLSX": "Excel Open XML Spreadsheet",
    "XLSM": "Excel Open XML Macro-Enabled Spreadsheet",
    "XLSB": "Excel Binary Spreadsheet",
    "CSV": "Comma-Separated Values",
    "PPT": "PowerPoint Presentation (Legacy)",
    "PPTX": "PowerPoint Open XML Presentation",
    "PPS": "PowerPoint Slide Show (Legacy)",
    "PPSX": "PowerPoint Open XML Slide Show",
    "POT": "PowerPoint Template (Legacy)",
    "POTX": "PowerPoint Open XML Template",
    "ACCDB": "Access Database (2007 or later)",
    "MDB": "Access Database (Legacy)",
    "PST": "Outlook Data File (Personal Storage Table)",
    "OST": "Outlook Offline Data File",
    "PUB": "Publisher Document",
    "ONE": "OneNote Document"
}
